### ISSUE TITLE
COMETS 1.4 Tagging and other issues in interactive mode

### ISSUE THREAD

**Issue by steven-moore** [CBIIT/R-cometsAnalytics#22]
Interactive mode - If using non-R friendly names for metabolites,  it would fail with “individual metabolite names” or use the tag function. (Comets R).  A lower priority issue for now.

**Comment by steven-moore** [comment]
[Scrambled.CPSII.data_comp_id_removed.xlsx](https://github.com/CBIIT/R-cometsAnalytics/files/2435378/Scrambled.CPSII.data_comp_id_removed.xlsx)

Ewy has changed the processing of metabolite names to make this an array-based system, but changes need to be made to the interface to fully capitalize on these changes.  There are at least two examples:

1. When making tags of metabolites, the metabolite names are not being properly mapped.  Thus, when you examine metabolite*metabolite correlations using a tag, it results in mismapped metabolites and an error.

![image](https://user-images.githubusercontent.com/34717005/46312194-5d89a900-c592-11e8-8fd5-e1b1bb6339fe.png)


2. When examining metabolite*metabolite correlations, names are dynamically updated for the outcomes (which is the intended functionality) but not for the exposures.

![image](https://user-images.githubusercontent.com/34717005/46312027-dd634380-c591-11e8-9cde-439b0c635dd9.png)

![image](https://user-images.githubusercontent.com/34717005/46311911-983f1180-c591-11e8-8054-53405d399e61.png)

**Comment by park-brian** [comment]
For item 2, the web application displays the outcome/exposure columns as-is from the correlation output. It looks like the outcome column's values have been mapped to the original metabolite names, but the exposure column does not map metabolite names: 

![image](https://user-images.githubusercontent.com/12477449/46438549-3535b200-c72c-11e8-8084-1b145a5ef0da.png)

```R
metab_data <- readCOMETSinput(system.file('extdata', 'cometsInputAge.xlsx', package = 'COMETS'))
model_data <- getModelData(metab_data, modelspec = 'Interactive', colvars = c('_1_2_3_benzenetriol_sulfate_2', '_1_2_dipalmitoylglycerol'), rowvars = c('_1_2_3_benzenetriol_sulfate_2', '_1_2_dipalmitoylglycerol'))
corr_data <- runCorr(model_data, metab_data)

View(corr_data)
```

**Comment by park-brian** [comment]
Yes, once the package is updated the UI should pick up the new names.

**Comment by steven-moore** [comment]
See also issue #42

**Comment by steven-moore** [comment]
Per our phone conversation today, Ella will look into this and issue #42 (the two issues are interrelated)

**Comment by steven-moore** [comment]
The heatmap issue has been resolved (point 1 above), but the reporting for exposure and outcome metabolites still differ (point 2).  I may be able to live with this, but we should at least discuss whether this is the functionality we want.

**Comment by steven-moore** [comment]
Fixed and closed
