### ISSUE TITLE
COMETS 1.4. UID file integration

### ISSUE THREAD

**Issue by ellatemprosa** [CBIIT/R-cometsAnalytics#30]
some weird UIDs to be checked:

- PC-source_fragment
- nh4 suffix

C14_0_CE_+NH4
C16_0_CE_+NH4
C16_1_CE_+NH4
C18_0_CE_+NH4
C18_0_MAG_+NH4
C18_1_CE_+NH4
C18_2_CE_+NH4

**Comment by steven-moore** [comment]
The first step is to have David prepare the R file directly.  This means that he will need a walkthrough from Ella or Ewy so that he knows how to run the function
