### ISSUE TITLE
COMETS 1.5 Rapid UID upload

### ISSUE THREAD

**Issue by nateappel** [CBIIT/R-cometsAnalytics#43]
After harmonization of study data, in our updated process, we will need to update COMETS with a new UID file to account for new metabolites added. Is there a way to automate this where when the files has changes, we can upload it to a specific spot and is used by COMETS without any input processing?

Does the file we send need to be modified to make something like this work.

**Comment by steven-moore** [comment]
Switched to COMETS 1.5, as this is intertwined with our update to a relational DB format for this file
