### ISSUE TITLE
COMETS 1.5 - Harmonization file variable defintions:  COMP_ID.Cohort,  COMP_ID.Comets, and COMP_ID 

### ISSUE THREAD

**Issue by nateappel** [CBIIT/R-cometsAnalytics#56]
Can you give us the differences between these 3 variables?

Also, why is the lone COMP_ID variable missing sometimes?

Thanks, 
Nate

**Comment by ellatemprosa** [comment]
will take with nate and david next week to clarify issue and address appropriately

**Comment by steven-moore** [comment]
The COMP_ID is from the original file.  It is only included for Metabolon data, for sample runs prior to ~2016.

As for the other two, I may need a bit of explanation myself.  Is it possible to eliminate one or the other of these?

**Comment by steven-moore** [comment]
Moved to COMETS 1.5--this will get resolved when we change the file to a relational database
