### ISSUE TITLE
COMETS 1.3. Amazon queue not managed correctly if 3+ jobs

### ISSUE THREAD

**Issue by steven-moore** [CBIIT/R-cometsAnalytics#60]
I tested this by running two jobs, logging out, and testing a third job.  The first two ran fine, but the third did not, and returned the error below the dotted line.  I have tested this a few times today with consistent results.

If the system is maxed out, we should at least send a different, more specific e-mail message.  Along the lines of "Apologies, but the queue for data analysis in COMETS-Analytics was at its maximum capacity when you submitted your data.  Please try again."

----
Dear COMETS user,

Due to an unexpected error, no meaningful results could be provided. Please contact the COMETS Web Tool team for assistance in resolving the issue.

Respectfully,

COMETS Web Tool

**Comment by kailingchen** [comment]
As described by Steve above, this issue should not happen in production. The production environment has 2 servers , one is the web server to process website requests and one is the queue processor to process supper-batch job. All the super-batch jobs will be queued and processed sequentially so it will never exceed the number of concurrent processes. In the test site, there is only one server to process both website requests and super-batch jobs.
