### ISSUE TITLE
1.5 Warning: "missing value where 'true/false' needed"

### ISSUE THREAD

**Issue by kmazzilli** [CBIIT/R-cometsAnalytics#62]
"missing value where 'true/false' needed" appears when groups have missing data.
![screen shot](https://user-images.githubusercontent.com/40246056/41991603-0060bbac-7a14-11e8-892f-7590278c6b72.PNG)

On 6/27 we discussed this with the Colocare cohort team and from 6/20-6/27 we discussed this with the Baependi Heart Study Team. For now we have told them to do one of three options: In place of the missing/blank values please input either a 0 or half the limit of detection or half of the lowest observed value.

**Comment by steven-moore** [comment]
This is a missing data issue
