### ISSUE TITLE
COMETS 1.5.  Adjusting for a metabolite when "all metabolites" is an outcome

### ISSUE THREAD

**Issue by steven-moore** [CBIIT/R-cometsAnalytics#69]
This model produces results for the metabolite being adjusted for but shouldn't (or should change what is listed in the adjustments columns).

![image](https://user-images.githubusercontent.com/34717005/49544430-d665f380-f8a8-11e8-9a0a-d03a890f852e.png)

**Comment by steven-moore** [comment]
This is still an issue, but is not serious and could be pushed to 1.5

**Comment by ellatemprosa** [comment]
Sounds like this is an index issue

**Comment by steven-moore** [comment]
Still an issue, but switched to COMETS 1.5 so that we can move 1.4 deployment forward.  We can discuss in more detail after we move forward our manuscript.
