### ISSUE TITLE
COMETS 1.4. In "DESCR" file produced when running "all models", metabolite array positions given instead of names

### ISSUE THREAD

**Issue by steven-moore** [CBIIT/R-cometsAnalytics#70]
See above, and screenshot below.

![image](https://user-images.githubusercontent.com/34717005/49754876-45ff2880-fc85-11e8-9566-9519e0cab8e6.png)

**Comment by kailingchen** [comment]
Deployed Ewy's changes to the test site. Please verify.

**Comment by steven-moore** [comment]
Issue still exists--spreadsheet is exact same as above.  Check "all models" functionality again?

**Comment by steven-moore** [comment]
After most recent build, "all models" functionality is halted completely--not even an e-mail to notify us of failure

**Comment by steven-moore** [comment]
Issue is resolved and closed.  COMETS 14. is complete and ready for production.
