### ISSUE TITLE
Vignette error

### ISSUE THREAD

**Issue by ellatemprosa** [CBIIT/R-cometsAnalytics#85]
when running the vignette from dev3.1 

`
> rlang::last_trace()
<error/rlang_error>
Error in `union_all()`:
! `x` and `y` are not compatible.
✖ Different number of columns: 16 vs 15.
---
Backtrace:
    ▆
 1. ├─RcometsAnalytics::readCOMETSinput("/Users/mathee/Downloads/cometsInputAge(7).xlsx")
 2. │ └─RcometsAnalytics:::Harmonize(dtalist)
 3. │   └─finharmlistg %>% filter(!is.na(uid_01)) %>% ...
 4. ├─dplyr::union_all(., foundhmdb)
 5. └─dplyr:::union_all.data.frame(., foundhmdb)
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.
`

**Comment by Mathelab** [comment]
This has been corrected.
